import Head from 'next/head';
import Image from 'next/image';
import Contact from '../components/Contact';
import Main from '../components/Main';
import Projects from '../components/Projects';
import Skills from '../components/Skills';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mohammed Benloucif | Full-Stack Dev </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://pngimg.com/uploads/letter_m/letter_m_PNG80.png" />
      </Head>
    <Main />
    <Skills />
    <Projects />
    


      </div>  
  )
}
